# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pyqt/pizza.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 539)
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-image: url(./images/Image_pizza.png);\n"
"}\n"
"QWidget#centralwidget{\n"
"background-color: rgba(85, 255, 255, 35);\n"
"}\n"
"QLabel{\n"
"    font: 22pt \"MS Reference Sans Serif\";\n"
"color: rgb(110, 17, 122);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(31, 31))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionplus = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/Image2png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionplus.setIcon(icon)
        self.actionplus.setObjectName("actionplus")
        self.actionminus = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/Image1png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionminus.setIcon(icon1)
        self.actionminus.setObjectName("actionminus")
        self.actionpizz = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./images/Image_pizza.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpizz.setIcon(icon2)
        self.actionpizz.setObjectName("actionpizz")
        self.toolBar.addAction(self.actionplus)
        self.toolBar.addAction(self.actionminus)
        self.toolBar.addAction(self.actionpizz)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Нажмите кнопку для заказа..."))
        self.pushButton.setText(_translate("MainWindow", "Заказать!"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionplus.setText(_translate("MainWindow", "plus"))
        self.actionminus.setText(_translate("MainWindow", "minus"))
        self.actionpizz.setText(_translate("MainWindow", "pizz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
